spring:
  application:
    name: eureka
server:
  port: 8761
  
---
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: prod
eureka:
  server:
    renewalPercentThreshold: 0.49
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: false
  
