spring:
  application:
    name: eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: ALL
server:
  port: 8761